// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthSigninComp: typeof import('./components/AuthSigninComp.vue')['default']
    AuthSignupComp: typeof import('./components/AuthSigninComp.vue')['default']
    AuthSignupDirectorComp: typeof import('./components/AuthSignupDirectorComp.vue')['default']
    AuthSignupStudentComp: typeof import('./components/AuthSignupStudentComp.vue')['default']
    AvatarEdit: typeof import('./components/AvatarEdit.vue')['default']
    ChangePassword: typeof import('./components/ChangePassword.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DrivingSchoolList: typeof import('./components/admin/DrivingSchool/DrivingSchoolList.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    FileUploader: typeof import('./components/FileUploader.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutHeaderAdmin: typeof import('./components/admin/LayoutHeaderAdmin.vue')['default']
    LayoutHeaderDirector: typeof import('./components/director/LayoutHeaderDirector.vue')['default']
    LayoutHeaderMonitor: typeof import('./components/monitor/LayoutHeaderMonitor.vue')['default']
    LayoutHeaderStudent: typeof import('./components/student/LayoutHeaderStudent.vue')['default']
    ListRoom: typeof import('./components/ListRoom.vue')['default']
    ListSlotComp: typeof import('./components/director/ListSlotComp.vue')['default']
    ListUser: typeof import('./components/ListUser.vue')['default']
    ModalEditBooking: typeof import('./components/director/ModalEditBooking.vue')['default']
    ModalEditBookingComp: typeof import('./components/director/ModalEditBookingComp.vue')['default']
    ModalEditBookingComp2: typeof import('./components/director/ModalEditBookingComp.vue')['default']
    MonitorList: typeof import('./components/director/Monitor/MonitorList.vue')['default']
    OneSignalStatus: typeof import('./components/OneSignalStatus.vue')['default']
    ProfileEdit: typeof import('./components/ProfileEdit.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QIcon: typeof import('quasar')['QIcon']
    QImg: typeof import('quasar')['QImg']
    QInput: typeof import('quasar')['QInput']
    QPage: typeof import('quasar')['QPage']
    QSelect: typeof import('quasar')['QSelect']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./components/admin/UserList.vue')['default']
  }
}
