// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthSigninComp: typeof import('./components/AuthSigninComp.vue')['default']
    AuthSignupDirectorComp: typeof import('./components/AuthSignupDirectorComp.vue')['default']
    AuthSignupStudentComp: typeof import('./components/AuthSignupStudentComp.vue')['default']
    DirectorList: typeof import('./components/admin/Director/DirectorList.vue')['default']
    DrivingSchoolList: typeof import('./components/admin/DrivingSchool/DrivingSchoolList.vue')['default']
    LayoutHeader: typeof import('./components/LayoutHeader.vue')['default']
    LayoutHeaderAdmin: typeof import('./components/admin/LayoutHeaderAdmin.vue')['default']
    LayoutHeaderDirector: typeof import('./components/director/LayoutHeaderDirector.vue')['default']
    LayoutHeaderMonitor: typeof import('./components/monitor/LayoutHeaderMonitor.vue')['default']
    LayoutHeaderStudent: typeof import('./components/student/LayoutHeaderStudent.vue')['default']
    ListSlotComp: typeof import('./components/director/ListSlotComp.vue')['default']
    ModalEditBookingComp: typeof import('./components/director/ModalEditBookingComp.vue')['default']
    MonitorList: typeof import('./components/director/Monitor/MonitorList.vue')['default']
    MonitorListAdmin: typeof import('./components/admin/Monitor/MonitorListAdmin.vue')['default']
    PackageListAdmin: typeof import('./components/admin/PackageAdmin/PackageListAdmin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentList: typeof import('./components/admin/Student/StudentList.vue')['default']
    UserList: typeof import('./components/admin/UserList.vue')['default']
  }
}
