controllers:
    resource: ../src/Controller/
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /authentication_token
    methods: ['POST']
