name: Deploy Drive Queen server

on:
  push:
    tags:
      - 'server-v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /kyc/
          local-dir: ./server/
          exclude: |
            **/.git*
            **/.github*
            **/.gitignore
            **/.gitattributes
            node_modules/**