name: Deploy Drive Queen front

on:
  push:
    tags:
      - 'front-v*'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name:  Checkout the front repository
      uses: actions/checkout@v2
    - name: Show files in frontend
      run: tree
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
      working-directory: ./frontend
    - name: Build Vite .env
      run: |
        echo "VITE_CHALLENGE_URL=${{ secrets.VITE_CHALLENGE_URL }}" >> .env
        echo "VITE_KYC_URL=${{ secrets.VITE_KYC_URL }}" >> .env
      working-directory: ./frontend
    - name: Build
      run: pnpm run build
      working-directory: ./frontend
    - name: Prepare app for target server
      env: 
        HTACCESS: ${{ secrets.HTACCESS }}
      run: |
        echo "${HTACCESS}" >> ./dist/.htaccess
        echo "https://drive-queen.turtletv.fr" >> ./dist/CNAME
        sed -i 's/<title>.*<\/title>/<title>Drive Queen<\/title>/g' ./dist/index.html
      working-directory: ./frontend
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /front/
        local-dir: ./frontend/dist/
        

     